#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $RAG_DB_USER WITH PASSWORD '$RAG_DB_PASSWORD';
    CREATE DATABASE $RAG_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $RAG_DB_NAME TO $RAG_DB_USER;
    \c $RAG_DB_NAME
    CREATE EXTENSION IF NOT EXISTS vector;
EOSQL