# Generated by Django 6.0.5 on 2026-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='embedding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
